@startuml

title __PROTECTSCOTLAND's Class Diagram__\n

  namespace protectscotland {
    class protectscotland.AboutThisApp {
        ~ driver : AndroidDriver<WebElement>
        - howDoesAppWorkText : By
        - moreAboutPrivacyNoticeButton : By
        - moreAboutScamsButton : By
        - moreAboutThisAppText : By
        + AboutThisApp()
        + checkABoutThisAppPageVisibility()
        + clickAvoidingScam()
        + clickMoreAppThisApp()
        + clickPrivacyNotice()
    }
  }
  

  namespace protectscotland {
    class protectscotland.AddTestCode {
        ~ driver : AndroidDriver<WebElement>
        - addATestCodeButton : By
        - bookATestButton : By
        - howDoesAppWorkText : By
        - moreAboutThisAppText : By
        + AddTestCode()
        + checkInAddTestCodePage()
        + clickAddATestCode()
        + clickBookATestButton()
        + clickMoreAppThisApp()
    }
  }
  

  namespace protectscotland {
    class protectscotland.AgeConfirmation {
        ~ driver : AndroidDriver<WebElement>
        - age12And15Button : By
        - ageConfirmationContainer : By
        - confirmAgePopup : By
        - over16Button : By
        - over16Warning : By
        - parentOptionalContainer : By
        - parentRequiredContainer : By
        - secondarySchoolContainer : By
        - under12Button : By
        + AgeConfirmation()
        + checkAgeConformation()
        + checkForAgeConfirmationPopup()
        + checkForSecondarySchoolConfirmationContainer()
        + checkIfInParentRequiredPage()
        + checkIfInParentsOptionalPage()
        + checkUnder12ButtonVisibility()
        + clickAgeBetween12And15()
        + clickOkToWarningMessage()
        + clickOver16()
        + clickUnder12()
    }
  }
  

  namespace protectscotland {
    class protectscotland.HomePage {
        ~ driver : AndroidDriver<WebElement>
        - aboutThisAppText : By
        - addTetCodeText : By
        - bluetoothPopupPanel : By
        - clickClose : By
        - homePageConfirmText : By
        - homePageTracingNotActiveConfirmText : By
        - shareAndProtectText : By
        - turnCovid : By
        + HomePage()
        + checkForExposureNotifications()
        + checkForHomePageTracingNotActive()
        + checkForTurnONExposureNotificationsPopup()
        + checkInHomePage()
        + clickAboutThisApp()
        + clickAddTestCode()
        + clickClose()
        + clickShareAndProtect()
        + clickTurnOn()
    }
  }
  

  namespace protectscotland {
    class protectscotland.LocationConfirmation {
        ~ driver : AndroidDriver<WebElement>
        - LocationWarningOk : By
        - invalidLocationPopup : By
        - locationContainer : By
        - noButton : By
        - yesButton : By
        + LocationConfirmation()
        + checkForInvalidLocationPopup()
        + checkLocationPageVisibility()
        + clickNo()
        + clickOkToWarningMessage()
        + clickYes()
    }
  }
  

  namespace protectscotland {
    class protectscotland.Navigation {
        ~ driver : AndroidDriver<WebElement>
        - backArrow : By
        - chromeUrlContainer : By
        - closeChromeButton : By
        - exitButton : By
        - nextButton : By
        - settingsButton : By
        + Navigation()
        + checkInChromeWebBrowser()
        + clickBackArrow()
        + clickCloseWebButton()
        + clickExit()
        + clickNext()
        + clickSettings()
    }
  }
  

  namespace protectscotland {
    class protectscotland.SettingsPage {
        ~ driver : AndroidDriver<WebElement>
        - backButton : By
        - datPrivacyButton : By
        - iWantToLeaveButton : By
        - leaveButton : By
        - over16Warning : By
        - termsAndConditionsButton : By
        + SettingsPage()
        + checkDataPrivacyPageVisibility()
        + checkLeavePageVisibility()
        + checkSettingPageVisibility()
        + checkTermsAndConditionsPageVisibility()
        + clickDatPrivacy()
        + clickIWantToLeave()
        + clickLeave()
        + clickTermsAndConditions()
    }
  }
  

  namespace protectscotland {
    class protectscotland.ShareAndProtect {
        ~ driver : AndroidDriver<WebElement>
        - restrictionsInYourAreaText : By
        - shareThisAppButton : By
        + ShareAndProtect()
        + checkInShareAndProtectPageVisibility()
        + clickRestrictionsInYourArea()
        + clickShareThisAppButton()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
