@startuml

title __ONBOARDING's Class Diagram__\n

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.BeFirstToKnowPage_2 {
          ~ driver : AndroidDriver<WebElement>
          - onBoardingStage2 : By
          - whatIsCloseContactText : By
          + BeFirstToKnowPage_2()
          + checkBeFirstToKnowPage()
          + checkForCloseContactText()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.BluetoothPermissionPage_7 {
          ~ driver : AndroidDriver<WebElement>
          - bluetoothPopupPanel : By
          - onBoardingStage7 : By
          + BluetoothPermissionPage_7()
          + checkForTurnONExposureNotificationsPopup()
          + checkIfInBluetoothPermissionsPage()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.ConsentAutomatedProcessingPage_5 {
          ~ driver : AndroidDriver<WebElement>
          - onBoardingStage5 : By
          - yesButton : By
          + ConsentAutomatedProcessingPage_5()
          + checkIfInAutomatedProcessingPage()
          + clickYes()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.GettingATestResultPage_3 {
          ~ driver : AndroidDriver<WebElement>
          - howDoIAddMyResult : By
          - onBoardingStage3 : By
          - positiveTestResultImage : By
          + GettingATestResultPage_3()
          + checkForForPositiveTestResultImage()
          + checkIfInGettingATestResultPage()
          + clickHowToAddMyTestResult()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.HelpOthersPage_1 {
          ~ driver : AndroidDriver<WebElement>
          - onBoardingStage1 : By
          + HelpOthersPage_1()
          + checkInHelpOtherPage()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.PrivacyInfoPage_4 {
          ~ driver : AndroidDriver<WebElement>
          - onBoardingStage4 : By
          + PrivacyInfoPage_4()
          + checkIfInPrivacyInfoPage()
      }
    }
  }
  

  namespace protectscotland {
    namespace onboarding {
      class protectscotland.onboarding.T_CPage_6 {
          ~ driver : AndroidDriver<WebElement>
          - onBoardingStage6 : By
          + T_CPage_6()
          + checkIfInTCPage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
